/**
 * Datos seed para el demo MORÁN.
 *
 * Diseñados para que cada pantalla principal de la PWA tenga contenido
 * realista y navegable sin que el usuario se choque con listas vacías.
 */

export const DEMO_ADMIN = {
  id: 1,
  name: "Admin Demo",
  email: "admin@moran.demo",
  role: "admin" as const,
  company: "Grupo Morán",
  avatarUrl: null,
  isActive: true,
  isRealUser: true,
  clerkId: "user_demo_admin",
  phone: "+52 55 1234 5678",
  createdAt: "2026-01-15T10:00:00.000Z",
  approvedAt: "2026-01-15T10:00:00.000Z",
};

export const DEMO_USERS = [
  DEMO_ADMIN,
  {
    id: 2,
    name: "Carlos Mendoza",
    email: "carlos.mendoza@moran.demo",
    role: "supervisor" as const,
    company: "Grupo Morán",
    avatarUrl: null,
    isActive: true,
    isRealUser: true,
    clerkId: "user_demo_supervisor",
    phone: "+52 55 2345 6789",
    createdAt: "2026-02-01T09:00:00.000Z",
    approvedAt: "2026-02-01T09:30:00.000Z",
  },
  {
    id: 3,
    name: "Laura Ramírez",
    email: "laura.ramirez@moran.demo",
    role: "supervisor" as const,
    company: "Grupo Morán",
    avatarUrl: null,
    isActive: true,
    isRealUser: true,
    clerkId: "user_demo_supervisor2",
    phone: "+52 55 3456 7890",
    createdAt: "2026-02-10T11:00:00.000Z",
    approvedAt: "2026-02-10T11:30:00.000Z",
  },
  {
    id: 4,
    name: "Roberto Silva",
    email: "roberto.silva@cliente.demo",
    role: "client" as const,
    company: "Inmobiliaria Polanco",
    avatarUrl: null,
    isActive: true,
    isRealUser: true,
    clerkId: "user_demo_client",
    phone: "+52 55 4567 8901",
    createdAt: "2026-03-01T10:00:00.000Z",
    approvedAt: "2026-03-01T10:30:00.000Z",
  },
  {
    id: 5,
    name: "María González",
    email: "maria.gonzalez@cliente.demo",
    role: "client" as const,
    company: "Desarrolladora Reforma",
    avatarUrl: null,
    isActive: true,
    isRealUser: true,
    clerkId: "user_demo_client2",
    phone: "+52 55 5678 9012",
    createdAt: "2026-03-15T10:00:00.000Z",
    approvedAt: "2026-03-15T10:30:00.000Z",
  },
  {
    id: 6,
    name: "Materiales del Norte",
    email: "ventas@mat-norte.demo",
    role: "proveedor" as const,
    company: "Materiales del Norte SA",
    avatarUrl: null,
    isActive: true,
    isRealUser: true,
    clerkId: "user_demo_proveedor",
    phone: "+52 81 1234 5678",
    createdAt: "2026-02-20T10:00:00.000Z",
    approvedAt: "2026-02-20T10:30:00.000Z",
  },
];

export const DEMO_PROJECTS = [
  {
    id: 1,
    name: "Torre Reforma 360",
    code: "TR360",
    address: "Av. Paseo de la Reforma 360, Ciudad de México",
    status: "active" as const,
    description: "Torre corporativa de 28 niveles con plaza comercial en planta baja. Acero y concreto premium.",
    coverUrl: "/project-1.png",
    budgetTotal: 145000000,
    budgetSpent: 87500000,
    progressPct: 62,
    startDate: "2025-09-15",
    targetDate: "2027-03-30",
    clientId: 4,
    clientName: "Inmobiliaria Polanco",
    supervisorId: 2,
    supervisorName: "Carlos Mendoza",
    createdAt: "2025-09-01T09:00:00.000Z",
  },
  {
    id: 2,
    name: "Residencial Bosques",
    code: "RB18",
    address: "Bosques de las Lomas, Ciudad de México",
    status: "active" as const,
    description: "18 residencias de lujo con amenidades comunes. Acabados de alta gama.",
    coverUrl: "/project-2.png",
    budgetTotal: 92000000,
    budgetSpent: 31200000,
    progressPct: 34,
    startDate: "2026-01-10",
    targetDate: "2027-08-15",
    clientId: 5,
    clientName: "Desarrolladora Reforma",
    supervisorId: 3,
    supervisorName: "Laura Ramírez",
    createdAt: "2025-12-15T09:00:00.000Z",
  },
  {
    id: 3,
    name: "Centro Logístico Querétaro",
    code: "CLQ",
    address: "Parque Industrial El Marqués, Querétaro",
    status: "active" as const,
    description: "Nave industrial de 24,000m² con 18 andenes de carga y oficinas administrativas.",
    coverUrl: "/project-3.png",
    budgetTotal: 68000000,
    budgetSpent: 65300000,
    progressPct: 96,
    startDate: "2025-04-01",
    targetDate: "2026-06-30",
    clientId: 4,
    clientName: "Inmobiliaria Polanco",
    supervisorId: 2,
    supervisorName: "Carlos Mendoza",
    createdAt: "2025-03-15T09:00:00.000Z",
  },
  {
    id: 4,
    name: "Plaza Vista Mar",
    code: "PVM",
    address: "Blvd. Costero 1500, Acapulco",
    status: "active" as const,
    description: "Centro comercial mixto frente al mar. 60 locales + 2 anclas + estacionamiento subterráneo.",
    coverUrl: "/project-4.png",
    budgetTotal: 110000000,
    budgetSpent: 18700000,
    progressPct: 17,
    startDate: "2026-03-20",
    targetDate: "2028-02-28",
    clientId: 5,
    clientName: "Desarrolladora Reforma",
    supervisorId: 3,
    supervisorName: "Laura Ramírez",
    createdAt: "2026-03-01T09:00:00.000Z",
  },
  {
    id: 5,
    name: "Hospital Regional Sur",
    code: "HRS",
    address: "Av. Universidad 800, Cuernavaca, Morelos",
    status: "completed" as const,
    description: "Hospital de 4 niveles con 120 camas. Entregado a tiempo y dentro de presupuesto.",
    coverUrl: "/project-5.png",
    budgetTotal: 89000000,
    budgetSpent: 88150000,
    progressPct: 100,
    startDate: "2024-02-01",
    targetDate: "2025-12-15",
    clientId: 4,
    clientName: "Inmobiliaria Polanco",
    supervisorId: 2,
    supervisorName: "Carlos Mendoza",
    createdAt: "2024-01-15T09:00:00.000Z",
  },
];

const today = new Date();
function daysAgo(n: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

export const DEMO_LOGS = [
  {
    id: 1,
    projectId: 1,
    projectName: "Torre Reforma 360",
    title: "Colado de losa nivel 18",
    description: "Se realizó el colado de losa del nivel 18 con concreto F'c 350. Personal completo, sin incidentes. Pruebas de revenimiento dentro de norma (8±2 cm). Próximo colado nivel 19 programado para el martes.",
    weather: "Despejado, 24°C",
    temperatura: 24,
    progressPct: 62,
    workersOnSite: 42,
    incidents: 0,
    createdBy: 2,
    createdByName: "Carlos Mendoza",
    createdAt: daysAgo(0),
    photos: [],
    signatures: [
      { role: "supervisor", name: "Carlos Mendoza", signedAt: daysAgo(0) },
    ],
  },
  {
    id: 2,
    projectId: 1,
    projectName: "Torre Reforma 360",
    title: "Inspección de soldaduras estructura nivel 17",
    description: "Inspección visual y por ultrasonido de soldaduras en perfiles W14x90 del nivel 17. Se identificaron 3 soldaduras con discontinuidades menores, se ordenó retrabajo. Resto OK.",
    weather: "Parcial nublado, 22°C",
    temperatura: 22,
    progressPct: 60,
    workersOnSite: 38,
    incidents: 1,
    createdBy: 2,
    createdByName: "Carlos Mendoza",
    createdAt: daysAgo(1),
    photos: [],
    signatures: [
      { role: "supervisor", name: "Carlos Mendoza", signedAt: daysAgo(1) },
      { role: "client", name: "Roberto Silva", signedAt: daysAgo(1) },
    ],
  },
  {
    id: 3,
    projectId: 2,
    projectName: "Residencial Bosques",
    title: "Excavación lote 7 y 8",
    description: "Se completó excavación de cimentación para lotes 7 y 8. Volumen total 320m³. Material retirado a banco autorizado. Próximo: armado de cimentación.",
    weather: "Despejado, 18°C",
    temperatura: 18,
    progressPct: 34,
    workersOnSite: 18,
    incidents: 0,
    createdBy: 3,
    createdByName: "Laura Ramírez",
    createdAt: daysAgo(0),
    photos: [],
    signatures: [
      { role: "supervisor", name: "Laura Ramírez", signedAt: daysAgo(0) },
    ],
  },
  {
    id: 4,
    projectId: 3,
    projectName: "Centro Logístico Querétaro",
    title: "Pruebas de acabados y entrega de andenes 12-18",
    description: "Se completó pruebas finales de los últimos 7 andenes. Niveladores hidráulicos funcionando. Pintura epóxica curada. Listos para entrega final el viernes.",
    weather: "Despejado, 28°C",
    temperatura: 28,
    progressPct: 96,
    workersOnSite: 12,
    incidents: 0,
    createdBy: 2,
    createdByName: "Carlos Mendoza",
    createdAt: daysAgo(2),
    photos: [],
    signatures: [
      { role: "supervisor", name: "Carlos Mendoza", signedAt: daysAgo(2) },
      { role: "client", name: "Roberto Silva", signedAt: daysAgo(1) },
    ],
  },
  {
    id: 5,
    projectId: 1,
    projectName: "Torre Reforma 360",
    title: "Instalación de fachada — módulos 12-24",
    description: "Avance de 13 módulos de fachada de cristal en nivel 15. Sellos confirmados. Próximos módulos llegan el lunes.",
    weather: "Soleado, 26°C",
    temperatura: 26,
    progressPct: 58,
    workersOnSite: 35,
    incidents: 0,
    createdBy: 2,
    createdByName: "Carlos Mendoza",
    createdAt: daysAgo(3),
    photos: [],
    signatures: [
      { role: "supervisor", name: "Carlos Mendoza", signedAt: daysAgo(3) },
    ],
  },
  {
    id: 6,
    projectId: 4,
    projectName: "Plaza Vista Mar",
    title: "Inicio de pilotes — zona A",
    description: "Arranque de hincado de pilotes en la zona A del estacionamiento subterráneo. 12 pilotes completados. Estudio de mecánica de suelos confirma capacidad de carga.",
    weather: "Cálido, 31°C",
    temperatura: 31,
    progressPct: 17,
    workersOnSite: 24,
    incidents: 0,
    createdBy: 3,
    createdByName: "Laura Ramírez",
    createdAt: daysAgo(1),
    photos: [],
    signatures: [
      { role: "supervisor", name: "Laura Ramírez", signedAt: daysAgo(1) },
    ],
  },
];

export const DEMO_MATERIALS = [
  {
    id: 1,
    projectId: 1,
    projectName: "Torre Reforma 360",
    name: "Concreto premezclado F'c 350",
    unit: "m³",
    quantity: 180,
    unitCost: 3200,
    totalCost: 576000,
    supplier: "Cemex",
    status: "approved" as const,
    requestedBy: 2,
    requestedByName: "Carlos Mendoza",
    approvedBy: 1,
    approvedByName: "Admin Demo",
    notes: "Para colado de losa nivel 18 — pruebas de revenimiento dentro de norma.",
    deliveryDate: daysAgo(0),
    createdAt: daysAgo(2),
  },
  {
    id: 2,
    projectId: 1,
    projectName: "Torre Reforma 360",
    name: "Varilla #5 corrugada",
    unit: "ton",
    quantity: 28,
    unitCost: 22500,
    totalCost: 630000,
    supplier: "Aceros Tultitlán",
    status: "approved" as const,
    requestedBy: 2,
    requestedByName: "Carlos Mendoza",
    approvedBy: 1,
    approvedByName: "Admin Demo",
    notes: "Refuerzo losa y columnas niveles 17-19",
    deliveryDate: daysAgo(3),
    createdAt: daysAgo(5),
  },
  {
    id: 3,
    projectId: 2,
    projectName: "Residencial Bosques",
    name: "Cimbra metálica de losa",
    unit: "pza",
    quantity: 240,
    unitCost: 850,
    totalCost: 204000,
    supplier: "Cimbras Industriales SA",
    status: "pending" as const,
    requestedBy: 3,
    requestedByName: "Laura Ramírez",
    approvedBy: null,
    approvedByName: null,
    notes: "Para losas de planta baja, lotes 1-8. Renta por 60 días.",
    deliveryDate: null,
    createdAt: daysAgo(1),
  },
  {
    id: 4,
    projectId: 4,
    projectName: "Plaza Vista Mar",
    name: "Pilotes prefabricados 18m",
    unit: "pza",
    quantity: 48,
    unitCost: 18500,
    totalCost: 888000,
    supplier: "Pilotes del Pacífico",
    status: "approved" as const,
    requestedBy: 3,
    requestedByName: "Laura Ramírez",
    approvedBy: 1,
    approvedByName: "Admin Demo",
    notes: "Pilotes para zonas A y B. Entrega escalonada.",
    deliveryDate: daysAgo(2),
    createdAt: daysAgo(7),
  },
  {
    id: 5,
    projectId: 3,
    projectName: "Centro Logístico Querétaro",
    name: "Pintura epóxica industrial (cubeta 19L)",
    unit: "cubeta",
    quantity: 35,
    unitCost: 2400,
    totalCost: 84000,
    supplier: "Comex",
    status: "approved" as const,
    requestedBy: 2,
    requestedByName: "Carlos Mendoza",
    approvedBy: 1,
    approvedByName: "Admin Demo",
    notes: "Acabado final de pisos en andenes 12-18.",
    deliveryDate: daysAgo(4),
    createdAt: daysAgo(6),
  },
  {
    id: 6,
    projectId: 1,
    projectName: "Torre Reforma 360",
    name: "Cristal templado fachada 12mm",
    unit: "m²",
    quantity: 320,
    unitCost: 1850,
    totalCost: 592000,
    supplier: "Vitro",
    status: "pending" as const,
    requestedBy: 2,
    requestedByName: "Carlos Mendoza",
    approvedBy: null,
    approvedByName: null,
    notes: "Módulos 25-40 de fachada nivel 16.",
    deliveryDate: null,
    createdAt: daysAgo(0),
  },
];

export const DEMO_DOCUMENTS = [
  {
    id: 1,
    projectId: 1,
    projectName: "Torre Reforma 360",
    name: "Planos arquitectónicos REV3.pdf",
    category: "planos" as const,
    fileUrl: "#",
    fileSize: 12800000,
    uploadedBy: 1,
    uploadedByName: "Admin Demo",
    createdAt: daysAgo(15),
  },
  {
    id: 2,
    projectId: 1,
    projectName: "Torre Reforma 360",
    name: "Memoria de cálculo estructural.pdf",
    category: "ingenieria" as const,
    fileUrl: "#",
    fileSize: 8400000,
    uploadedBy: 1,
    uploadedByName: "Admin Demo",
    createdAt: daysAgo(20),
  },
  {
    id: 3,
    projectId: 2,
    projectName: "Residencial Bosques",
    name: "Permiso construcción municipal.pdf",
    category: "legales" as const,
    fileUrl: "#",
    fileSize: 1200000,
    uploadedBy: 1,
    uploadedByName: "Admin Demo",
    createdAt: daysAgo(45),
  },
  {
    id: 4,
    projectId: 3,
    projectName: "Centro Logístico Querétaro",
    name: "Contrato cliente firmado.pdf",
    category: "contratos" as const,
    fileUrl: "#",
    fileSize: 2800000,
    uploadedBy: 1,
    uploadedByName: "Admin Demo",
    createdAt: daysAgo(380),
  },
];

export const DEMO_NOTIFICATIONS = [
  {
    id: 1,
    userId: 1,
    title: "Nueva bitácora — Torre Reforma 360",
    body: "Carlos Mendoza publicó: Colado de losa nivel 18",
    link: "/bitacora/1",
    type: "log_created" as const,
    isRead: false,
    createdAt: daysAgo(0),
  },
  {
    id: 2,
    userId: 1,
    title: "Material pendiente de aprobación",
    body: "Cimbra metálica de losa — Residencial Bosques · $204,000",
    link: "/materiales",
    type: "material_pending" as const,
    isRead: false,
    createdAt: daysAgo(1),
  },
  {
    id: 3,
    userId: 1,
    title: "Material pendiente de aprobación",
    body: "Cristal templado fachada — Torre Reforma 360 · $592,000",
    link: "/materiales",
    type: "material_pending" as const,
    isRead: false,
    createdAt: daysAgo(0),
  },
];

export const DEMO_CONTENT = {
  faq: [
    { id: 1, category: "Bitácora", title: "¿Cómo creo una entrada de bitácora?", body: "Ve a la pestaña 'Bitácora' y toca el botón '+'. Llena los campos obligatorios y firma con tu dedo. Las firmas se persisten atómicamente al guardar.", order: 1 },
    { id: 2, category: "Materiales", title: "¿Quién puede aprobar materiales?", body: "Sólo administradores. Los supervisores pueden solicitar materiales y verlos pendientes; el admin aprueba o rechaza desde su panel.", order: 2 },
    { id: 3, category: "Proyectos", title: "¿Cómo asigno un supervisor a un proyecto?", body: "Desde 'Proyectos' → abre el proyecto → 'Editar' → selecciona el supervisor en el dropdown.", order: 3 },
    { id: 4, category: "Cuenta", title: "¿Cómo cambio mi contraseña?", body: "Ve a 'Mi cuenta' → 'Cambiar contraseña' y sigue las instrucciones.", order: 4 },
    { id: 5, category: "Notificaciones", title: "¿Cómo activo las notificaciones push?", body: "En iOS necesitas instalar la app a tu pantalla de inicio (Compartir → Añadir a Pantalla de Inicio). Después, en 'Mi cuenta' → 'Notificaciones'.", order: 5 },
  ],
  terms: [
    { id: 1, title: "Aceptación del servicio", body: "Al usar Morán Control aceptas los presentes términos de uso. El sistema es de uso exclusivo del personal autorizado por Grupo Morán." },
    { id: 2, title: "Uso responsable", body: "El usuario es responsable de la veracidad de la información que captura: bitácoras, fotos, firmas, materiales y reportes." },
  ],
  privacy: [
    { id: 1, title: "Datos personales", body: "Recopilamos nombre, correo, teléfono y ubicación geográfica (sólo durante checks de asistencia) para la operación del sistema." },
    { id: 2, title: "Compartición", body: "No compartimos datos con terceros excepto cuando es necesario para la operación (Clerk para autenticación, base de datos Postgres alojada en Neon)." },
  ],
  announcement: [],
};

export const DEMO_PERMISSIONS = {
  // Admin demo: tiene todos los permisos posibles
  role: "admin" as const,
  permissions: {
    projects: { view: true, create: true, edit: true, delete: true },
    logs: { view: true, create: true, edit: true, delete: true, sign: true },
    materials: { view: true, create: true, edit: true, delete: true, approve: true },
    documents: { view: true, create: true, edit: true, delete: true },
    reports: { view: true, create: true, export: true },
    users: { view: true, create: true, edit: true, delete: true, approve: true },
    notifications: { view: true, send: true },
    admin: { audit: true, settings: true, invitations: true },
    attendance: { view: true, manage: true, qr: true },
  },
};
