/**
 * Datos seed para el demo MORÁN, alineados al schema generado por
 * orval (lib/api-zod/src/generated/types).
 */

const now = new Date();
function daysAgo(n: number): Date {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return d;
}
function daysAhead(n: number): Date {
  const d = new Date(now);
  d.setDate(d.getDate() + n);
  return d;
}
function iso(d: Date): string {
  return d.toISOString();
}

export const DEMO_ADMIN = {
  id: 1,
  name: "Admin Demo",
  email: "admin@moran.demo",
  role: "admin" as const,
  company: "Grupo Morán",
  avatarUrl: null,
  isActive: true,
  isRealUser: true,
  clerkId: "user_demo_admin",
  phone: "+52 55 1234 5678",
  createdAt: iso(daysAgo(120)),
  approvalStatus: "approved" as const,
};

export const DEMO_USERS = [
  DEMO_ADMIN,
  { id: 2, name: "Carlos Mendoza", email: "carlos.mendoza@moran.demo", role: "supervisor" as const, company: "Grupo Morán", avatarUrl: null, isActive: true, phone: "+52 55 2345 6789", createdAt: iso(daysAgo(110)) },
  { id: 3, name: "Laura Ramírez", email: "laura.ramirez@moran.demo", role: "supervisor" as const, company: "Grupo Morán", avatarUrl: null, isActive: true, phone: "+52 55 3456 7890", createdAt: iso(daysAgo(100)) },
  { id: 4, name: "Roberto Silva", email: "roberto.silva@cliente.demo", role: "client" as const, company: "Inmobiliaria Polanco", avatarUrl: null, isActive: true, phone: "+52 55 4567 8901", createdAt: iso(daysAgo(85)) },
  { id: 5, name: "María González", email: "maria.gonzalez@cliente.demo", role: "client" as const, company: "Desarrolladora Reforma", avatarUrl: null, isActive: true, phone: "+52 55 5678 9012", createdAt: iso(daysAgo(70)) },
  { id: 6, name: "Materiales del Norte SA", email: "ventas@mat-norte.demo", role: "proveedor" as const, company: "Materiales del Norte", avatarUrl: null, isActive: true, phone: "+52 81 1234 5678", createdAt: iso(daysAgo(95)) },
  { id: 7, name: "Juan Hernández", email: "juan.hernandez@moran.demo", role: "worker" as const, company: "Grupo Morán", avatarUrl: null, isActive: true, phone: "+52 55 6789 0123", createdAt: iso(daysAgo(60)) },
  { id: 8, name: "Pedro López", email: "pedro.lopez@moran.demo", role: "worker" as const, company: "Grupo Morán", avatarUrl: null, isActive: true, phone: "+52 55 7890 1234", createdAt: iso(daysAgo(55)) },
];

export const DEMO_PROJECTS = [
  {
    id: 1,
    name: "Torre Reforma 360",
    description: "Torre corporativa de 28 niveles con plaza comercial en planta baja. Acero y concreto premium.",
    clientId: 4,
    clientName: "Inmobiliaria Polanco",
    supervisorId: 2,
    supervisorName: "Carlos Mendoza",
    location: "Av. Paseo de la Reforma 360, Ciudad de México",
    latitude: 19.4267,
    longitude: -99.1718,
    startDate: iso(daysAgo(250)),
    endDate: iso(daysAhead(450)),
    budget: 145000000,
    spentAmount: 87500000,
    progressPercent: 62,
    status: "active" as const,
    coverImageUrl: "/project-1.png",
    createdAt: iso(daysAgo(260)),
    updatedAt: iso(daysAgo(1)),
  },
  {
    id: 2,
    name: "Residencial Bosques",
    description: "18 residencias de lujo con amenidades comunes. Acabados de alta gama.",
    clientId: 5,
    clientName: "Desarrolladora Reforma",
    supervisorId: 3,
    supervisorName: "Laura Ramírez",
    location: "Bosques de las Lomas, Ciudad de México",
    latitude: 19.4045,
    longitude: -99.2640,
    startDate: iso(daysAgo(140)),
    endDate: iso(daysAhead(580)),
    budget: 92000000,
    spentAmount: 31200000,
    progressPercent: 34,
    status: "active" as const,
    coverImageUrl: "/project-2.png",
    createdAt: iso(daysAgo(150)),
    updatedAt: iso(daysAgo(2)),
  },
  {
    id: 3,
    name: "Centro Logístico Querétaro",
    description: "Nave industrial de 24,000m² con 18 andenes de carga y oficinas administrativas.",
    clientId: 4,
    clientName: "Inmobiliaria Polanco",
    supervisorId: 2,
    supervisorName: "Carlos Mendoza",
    location: "Parque Industrial El Marqués, Querétaro",
    latitude: 20.6203,
    longitude: -100.3920,
    startDate: iso(daysAgo(420)),
    endDate: iso(daysAhead(35)),
    budget: 68000000,
    spentAmount: 65300000,
    progressPercent: 96,
    status: "active" as const,
    coverImageUrl: "/project-3.png",
    createdAt: iso(daysAgo(430)),
    updatedAt: iso(daysAgo(2)),
  },
  {
    id: 4,
    name: "Plaza Vista Mar",
    description: "Centro comercial mixto frente al mar. 60 locales + 2 anclas + estacionamiento subterráneo.",
    clientId: 5,
    clientName: "Desarrolladora Reforma",
    supervisorId: 3,
    supervisorName: "Laura Ramírez",
    location: "Blvd. Costero 1500, Acapulco",
    latitude: 16.8634,
    longitude: -99.8901,
    startDate: iso(daysAgo(60)),
    endDate: iso(daysAhead(720)),
    budget: 110000000,
    spentAmount: 18700000,
    progressPercent: 17,
    status: "active" as const,
    coverImageUrl: "/project-4.png",
    createdAt: iso(daysAgo(75)),
    updatedAt: iso(daysAgo(1)),
  },
  {
    id: 5,
    name: "Hospital Regional Sur",
    description: "Hospital de 4 niveles con 120 camas. Entregado a tiempo y dentro de presupuesto.",
    clientId: 4,
    clientName: "Inmobiliaria Polanco",
    supervisorId: 2,
    supervisorName: "Carlos Mendoza",
    location: "Av. Universidad 800, Cuernavaca, Morelos",
    latitude: 18.9261,
    longitude: -99.2308,
    startDate: iso(daysAgo(720)),
    endDate: iso(daysAgo(160)),
    budget: 89000000,
    spentAmount: 88150000,
    progressPercent: 100,
    status: "completed" as const,
    coverImageUrl: "/project-5.png",
    createdAt: iso(daysAgo(730)),
    updatedAt: iso(daysAgo(160)),
  },
];

export const DEMO_LOGS = [
  {
    id: 1,
    projectId: 1,
    projectName: "Torre Reforma 360",
    supervisorId: 2,
    supervisorName: "Carlos Mendoza",
    logDate: iso(daysAgo(0)),
    activity: "Colado de losa nivel 18",
    observations: "Se realizó el colado de losa del nivel 18 con concreto F'c 350. Personal completo, sin incidentes. Pruebas de revenimiento dentro de norma (8±2 cm). Próximo colado nivel 19 programado para el martes.",
    workersInvolved: "42 trabajadores: 8 albañiles, 18 ayudantes, 6 fierreros, 4 carpinteros, 2 operadores de bomba, 4 supervisores de calidad.",
    materialsUsed: "180 m³ de concreto F'c 350, 28 ton de varilla #5, cimbra metálica recuperada de niveles 16-17.",
    photos: [],
    supervisorSignature: "data:image/png;base64,demo",
    clientSignature: null,
    isSubmitted: true,
    submittedAt: iso(daysAgo(0)),
    createdAt: iso(daysAgo(0)),
    updatedAt: iso(daysAgo(0)),
  },
  {
    id: 2,
    projectId: 1,
    projectName: "Torre Reforma 360",
    supervisorId: 2,
    supervisorName: "Carlos Mendoza",
    logDate: iso(daysAgo(1)),
    activity: "Inspección de soldaduras estructura nivel 17",
    observations: "Inspección visual y por ultrasonido de soldaduras en perfiles W14x90 del nivel 17. Se identificaron 3 soldaduras con discontinuidades menores, se ordenó retrabajo. Resto OK.",
    workersInvolved: "38 trabajadores incluyendo 4 inspectores certificados de soldadura.",
    materialsUsed: "Equipo de inspección por ultrasonido, electrodos E70-18 para retrabajos.",
    photos: [],
    supervisorSignature: "data:image/png;base64,demo",
    clientSignature: "data:image/png;base64,demo",
    isSubmitted: true,
    submittedAt: iso(daysAgo(1)),
    createdAt: iso(daysAgo(1)),
    updatedAt: iso(daysAgo(1)),
  },
  {
    id: 3,
    projectId: 2,
    projectName: "Residencial Bosques",
    supervisorId: 3,
    supervisorName: "Laura Ramírez",
    logDate: iso(daysAgo(0)),
    activity: "Excavación lotes 7 y 8",
    observations: "Se completó excavación de cimentación para lotes 7 y 8. Volumen total 320 m³. Material retirado a banco autorizado. Próximo: armado de cimentación.",
    workersInvolved: "18 trabajadores con 2 retroexcavadoras y 3 volteos.",
    materialsUsed: "Diésel para maquinaria, no se aplicaron insumos de construcción aún.",
    photos: [],
    supervisorSignature: "data:image/png;base64,demo",
    clientSignature: null,
    isSubmitted: true,
    submittedAt: iso(daysAgo(0)),
    createdAt: iso(daysAgo(0)),
    updatedAt: iso(daysAgo(0)),
  },
  {
    id: 4,
    projectId: 3,
    projectName: "Centro Logístico Querétaro",
    supervisorId: 2,
    supervisorName: "Carlos Mendoza",
    logDate: iso(daysAgo(2)),
    activity: "Pruebas de acabados y entrega de andenes 12-18",
    observations: "Se completaron las pruebas finales de los últimos 7 andenes. Niveladores hidráulicos funcionando. Pintura epóxica curada. Listos para entrega final el viernes.",
    workersInvolved: "12 trabajadores y 2 técnicos especialistas en niveladores hidráulicos.",
    materialsUsed: "Selladores acrílicos, pruebas con monta cargas de 5 ton.",
    photos: [],
    supervisorSignature: "data:image/png;base64,demo",
    clientSignature: "data:image/png;base64,demo",
    isSubmitted: true,
    submittedAt: iso(daysAgo(2)),
    createdAt: iso(daysAgo(2)),
    updatedAt: iso(daysAgo(1)),
  },
  {
    id: 5,
    projectId: 1,
    projectName: "Torre Reforma 360",
    supervisorId: 2,
    supervisorName: "Carlos Mendoza",
    logDate: iso(daysAgo(3)),
    activity: "Instalación de fachada — módulos 12-24",
    observations: "Avance de 13 módulos de fachada de cristal en nivel 15. Sellos confirmados. Próximos módulos llegan el lunes.",
    workersInvolved: "35 trabajadores. 4 cuadrillas de instalación de cristal y 1 cuadrilla de sellado.",
    materialsUsed: "13 módulos prefabricados de fachada, sellador estructural Dow 995, accesorios.",
    photos: [],
    supervisorSignature: "data:image/png;base64,demo",
    clientSignature: null,
    isSubmitted: true,
    submittedAt: iso(daysAgo(3)),
    createdAt: iso(daysAgo(3)),
    updatedAt: iso(daysAgo(3)),
  },
  {
    id: 6,
    projectId: 4,
    projectName: "Plaza Vista Mar",
    supervisorId: 3,
    supervisorName: "Laura Ramírez",
    logDate: iso(daysAgo(1)),
    activity: "Inicio de hincado de pilotes zona A",
    observations: "Arranque de hincado de pilotes en la zona A del estacionamiento subterráneo. 12 pilotes completados. Estudio de mecánica de suelos confirma capacidad de carga.",
    workersInvolved: "24 trabajadores incluyendo cuadrilla de hincado especializada y 2 ingenieros geotécnicos.",
    materialsUsed: "12 pilotes prefabricados de 18m, martillos hidráulicos.",
    photos: [],
    supervisorSignature: "data:image/png;base64,demo",
    clientSignature: null,
    isSubmitted: true,
    submittedAt: iso(daysAgo(1)),
    createdAt: iso(daysAgo(1)),
    updatedAt: iso(daysAgo(1)),
  },
];

export const DEMO_MATERIALS = [
  {
    id: 1,
    projectId: 1,
    projectName: "Torre Reforma 360",
    requestedById: 2,
    requestedByName: "Carlos Mendoza",
    name: "Concreto premezclado F'c 350",
    description: "Para colado de losa nivel 18 — pruebas de revenimiento dentro de norma.",
    unit: "m³",
    quantityRequested: 180,
    quantityApproved: 180,
    quantityUsed: 180,
    costPerUnit: 3200,
    totalCost: 576000,
    status: "approved" as const,
    approvedById: 1,
    approvedByName: "Admin Demo",
    approvedAt: iso(daysAgo(2)),
    notes: "Entregado puntual por Cemex.",
    createdAt: iso(daysAgo(3)),
    updatedAt: iso(daysAgo(0)),
  },
  {
    id: 2,
    projectId: 1,
    projectName: "Torre Reforma 360",
    requestedById: 2,
    requestedByName: "Carlos Mendoza",
    name: "Varilla #5 corrugada",
    description: "Refuerzo losa y columnas niveles 17-19",
    unit: "ton",
    quantityRequested: 28,
    quantityApproved: 28,
    quantityUsed: 26,
    costPerUnit: 22500,
    totalCost: 630000,
    status: "approved" as const,
    approvedById: 1,
    approvedByName: "Admin Demo",
    approvedAt: iso(daysAgo(5)),
    notes: null,
    createdAt: iso(daysAgo(6)),
    updatedAt: iso(daysAgo(3)),
  },
  {
    id: 3,
    projectId: 2,
    projectName: "Residencial Bosques",
    requestedById: 3,
    requestedByName: "Laura Ramírez",
    name: "Cimbra metálica de losa",
    description: "Para losas de planta baja, lotes 1-8. Renta por 60 días.",
    unit: "pza",
    quantityRequested: 240,
    quantityApproved: null,
    quantityUsed: 0,
    costPerUnit: 850,
    totalCost: 204000,
    status: "pending" as const,
    approvedById: null,
    approvedByName: null,
    approvedAt: null,
    notes: "Pendiente de aprobación.",
    createdAt: iso(daysAgo(1)),
    updatedAt: iso(daysAgo(1)),
  },
  {
    id: 4,
    projectId: 4,
    projectName: "Plaza Vista Mar",
    requestedById: 3,
    requestedByName: "Laura Ramírez",
    name: "Pilotes prefabricados 18m",
    description: "Pilotes para zonas A y B. Entrega escalonada.",
    unit: "pza",
    quantityRequested: 48,
    quantityApproved: 48,
    quantityUsed: 12,
    costPerUnit: 18500,
    totalCost: 888000,
    status: "approved" as const,
    approvedById: 1,
    approvedByName: "Admin Demo",
    approvedAt: iso(daysAgo(6)),
    notes: null,
    createdAt: iso(daysAgo(7)),
    updatedAt: iso(daysAgo(1)),
  },
  {
    id: 5,
    projectId: 3,
    projectName: "Centro Logístico Querétaro",
    requestedById: 2,
    requestedByName: "Carlos Mendoza",
    name: "Pintura epóxica industrial 19L",
    description: "Acabado final de pisos en andenes 12-18.",
    unit: "cubeta",
    quantityRequested: 35,
    quantityApproved: 35,
    quantityUsed: 35,
    costPerUnit: 2400,
    totalCost: 84000,
    status: "approved" as const,
    approvedById: 1,
    approvedByName: "Admin Demo",
    approvedAt: iso(daysAgo(5)),
    notes: "Color RAL 7035 (gris claro).",
    createdAt: iso(daysAgo(6)),
    updatedAt: iso(daysAgo(2)),
  },
  {
    id: 6,
    projectId: 1,
    projectName: "Torre Reforma 360",
    requestedById: 2,
    requestedByName: "Carlos Mendoza",
    name: "Cristal templado fachada 12mm",
    description: "Módulos 25-40 de fachada nivel 16.",
    unit: "m²",
    quantityRequested: 320,
    quantityApproved: null,
    quantityUsed: 0,
    costPerUnit: 1850,
    totalCost: 592000,
    status: "pending" as const,
    approvedById: null,
    approvedByName: null,
    approvedAt: null,
    notes: "Cotización Vitro vigente.",
    createdAt: iso(daysAgo(0)),
    updatedAt: iso(daysAgo(0)),
  },
];

export const DEMO_DOCUMENTS = [
  { id: 1, projectId: 1, projectName: "Torre Reforma 360", uploadedById: 1, uploadedByName: "Admin Demo", title: "Planos arquitectónicos REV3", description: "Planos arquitectónicos revisión 3", category: "planos" as const, fileUrl: "#", fileSize: 12800000, mimeType: "application/pdf", createdAt: iso(daysAgo(15)) },
  { id: 2, projectId: 1, projectName: "Torre Reforma 360", uploadedById: 1, uploadedByName: "Admin Demo", title: "Memoria de cálculo estructural", description: "Memoria estructural", category: "ingenieria" as const, fileUrl: "#", fileSize: 8400000, mimeType: "application/pdf", createdAt: iso(daysAgo(20)) },
  { id: 3, projectId: 2, projectName: "Residencial Bosques", uploadedById: 1, uploadedByName: "Admin Demo", title: "Permiso construcción municipal", description: "Permiso municipal vigente", category: "permisos" as const, fileUrl: "#", fileSize: 1200000, mimeType: "application/pdf", createdAt: iso(daysAgo(45)) },
  { id: 4, projectId: 3, projectName: "Centro Logístico Querétaro", uploadedById: 1, uploadedByName: "Admin Demo", title: "Contrato cliente firmado", description: "Contrato firmado por ambas partes", category: "contratos" as const, fileUrl: "#", fileSize: 2800000, mimeType: "application/pdf", createdAt: iso(daysAgo(380)) },
];

export const DEMO_NOTIFICATIONS = [
  { id: 1, userId: 1, title: "Nueva bitácora — Torre Reforma 360", message: "Carlos Mendoza publicó: Colado de losa nivel 18", type: "log" as const, relatedId: 1, relatedType: "log", isRead: false, createdAt: iso(daysAgo(0)) },
  { id: 2, userId: 1, title: "Material pendiente de aprobación", message: "Cimbra metálica — Residencial Bosques · $204,000 MXN", type: "material" as const, relatedId: 3, relatedType: "material", isRead: false, createdAt: iso(daysAgo(1)) },
  { id: 3, userId: 1, title: "Material pendiente de aprobación", message: "Cristal templado fachada — Torre Reforma 360 · $592,000 MXN", type: "material" as const, relatedId: 6, relatedType: "material", isRead: false, createdAt: iso(daysAgo(0)) },
];

export const DEMO_ACTIVITY: Array<{
  id: number;
  type: "log" | "material" | "user" | "project" | "document";
  description: string;
  userId: number | null;
  userName: string | null;
  projectId: number | null;
  projectName: string | null;
  createdAt: string;
}> = [
  { id: 1, type: "log", description: "Carlos Mendoza registró bitácora: Colado de losa nivel 18", userId: 2, userName: "Carlos Mendoza", projectId: 1, projectName: "Torre Reforma 360", createdAt: iso(daysAgo(0)) },
  { id: 2, type: "material", description: "Solicitud de Cristal templado fachada 12mm ($592,000)", userId: 2, userName: "Carlos Mendoza", projectId: 1, projectName: "Torre Reforma 360", createdAt: iso(daysAgo(0)) },
  { id: 3, type: "log", description: "Laura Ramírez registró bitácora: Excavación lotes 7 y 8", userId: 3, userName: "Laura Ramírez", projectId: 2, projectName: "Residencial Bosques", createdAt: iso(daysAgo(0)) },
  { id: 4, type: "material", description: "Solicitud de Cimbra metálica de losa ($204,000)", userId: 3, userName: "Laura Ramírez", projectId: 2, projectName: "Residencial Bosques", createdAt: iso(daysAgo(1)) },
  { id: 5, type: "log", description: "Laura Ramírez registró bitácora: Hincado de pilotes zona A", userId: 3, userName: "Laura Ramírez", projectId: 4, projectName: "Plaza Vista Mar", createdAt: iso(daysAgo(1)) },
  { id: 6, type: "log", description: "Carlos Mendoza registró bitácora: Pruebas de acabados", userId: 2, userName: "Carlos Mendoza", projectId: 3, projectName: "Centro Logístico Querétaro", createdAt: iso(daysAgo(2)) },
];

export const DEMO_CONTENT = {
  faq: [
    { id: 1, type: "faq", title: "¿Cómo creo una entrada de bitácora?", body: "Ve a la pestaña 'Bitácora' y toca el botón '+'. Llena los campos obligatorios y firma con tu dedo. Las firmas se persisten atómicamente al guardar.", isActive: true, createdAt: iso(daysAgo(60)) },
    { id: 2, type: "faq", title: "¿Quién puede aprobar materiales?", body: "Sólo administradores. Los supervisores pueden solicitar materiales y verlos pendientes; el admin aprueba o rechaza desde su panel.", isActive: true, createdAt: iso(daysAgo(60)) },
    { id: 3, type: "faq", title: "¿Cómo asigno un supervisor a un proyecto?", body: "Desde 'Proyectos' → abre el proyecto → 'Editar' → selecciona el supervisor en el dropdown.", isActive: true, createdAt: iso(daysAgo(60)) },
    { id: 4, type: "faq", title: "¿Cómo cambio mi contraseña?", body: "Ve a 'Mi cuenta' → 'Cambiar contraseña' y sigue las instrucciones.", isActive: true, createdAt: iso(daysAgo(60)) },
    { id: 5, type: "faq", title: "¿Cómo activo las notificaciones push?", body: "En iOS necesitas instalar la app a tu pantalla de inicio (Compartir → Añadir a Pantalla de Inicio). Después, en 'Mi cuenta' → 'Notificaciones'.", isActive: true, createdAt: iso(daysAgo(60)) },
  ],
  terms: [
    { id: 10, type: "terms", title: "Aceptación del servicio", body: "Al usar Morán Control aceptas los presentes términos de uso. El sistema es de uso exclusivo del personal autorizado por Grupo Morán.", isActive: true, createdAt: iso(daysAgo(90)) },
    { id: 11, type: "terms", title: "Uso responsable", body: "El usuario es responsable de la veracidad de la información que captura: bitácoras, fotos, firmas, materiales y reportes.", isActive: true, createdAt: iso(daysAgo(90)) },
  ],
  privacy: [
    { id: 20, type: "privacy", title: "Datos personales", body: "Recopilamos nombre, correo, teléfono y ubicación geográfica (sólo durante checks de asistencia) para la operación del sistema.", isActive: true, createdAt: iso(daysAgo(90)) },
    { id: 21, type: "privacy", title: "Compartición", body: "No compartimos datos con terceros excepto cuando es necesario para la operación.", isActive: true, createdAt: iso(daysAgo(90)) },
  ],
  announcement: [] as unknown[],
};

export const DEMO_PERMISSIONS = {
  role: "admin" as const,
  permissions: {
    projects: { view: true, create: true, edit: true, delete: true },
    logs: { view: true, create: true, edit: true, delete: true, sign: true },
    materials: { view: true, create: true, edit: true, delete: true, approve: true },
    documents: { view: true, create: true, edit: true, delete: true },
    reports: { view: true, create: true, export: true },
    users: { view: true, create: true, edit: true, delete: true, approve: true },
    notifications: { view: true, send: true },
    admin: { audit: true, settings: true, invitations: true },
    attendance: { view: true, manage: true, qr: true },
  },
};

export function buildDashboardSummary() {
  const activeProjects = DEMO_PROJECTS.filter((p) => p.status === "active");
  const completedProjects = DEMO_PROJECTS.filter((p) => p.status === "completed");
  return {
    activeProjects: activeProjects.length,
    completedProjects: completedProjects.length,
    totalProjects: DEMO_PROJECTS.length,
    totalWorkers: DEMO_USERS.filter((u) => u.role === "worker").length + 78,
    totalSupervisors: DEMO_USERS.filter((u) => u.role === "supervisor").length,
    totalClients: DEMO_USERS.filter((u) => u.role === "client").length,
    pendingMaterialRequests: DEMO_MATERIALS.filter((m) => m.status === "pending").length,
    unreadNotifications: DEMO_NOTIFICATIONS.filter((n) => !n.isRead).length,
    totalLogsToday: DEMO_LOGS.filter((l) => {
      const d = new Date(l.createdAt);
      return d.toDateString() === new Date().toDateString();
    }).length,
    totalBudget: DEMO_PROJECTS.reduce((s, p) => s + p.budget, 0),
    totalSpent: DEMO_PROJECTS.reduce((s, p) => s + p.spentAmount, 0),
  };
}
