import {
  TbDashboard,
  TbBuildingSkyscraper,
  TbClipboardList,
  TbPackage,
  TbFileDescription,
  TbReportAnalytics,
  TbUsers,
  TbBell,
  TbLogout,
  TbMenu2,
  TbX,
  TbPlus,
  TbCalendar,
  TbMapPin,
  TbUser,
  TbSearch,
  TbFilter,
  TbDownload,
  TbEye,
  TbEdit,
  TbTrash,
  TbCheck,
  TbAlertTriangle,
  TbUpload,
  TbCamera,
} from "react-icons/tb";

export const Icons = {
  Dashboard: TbDashboard,
  Projects: TbBuildingSkyscraper,
  Logs: TbClipboardList,
  Materials: TbPackage,
  Documents: TbFileDescription,
  Reports: TbReportAnalytics,
  Users: TbUsers,
  Notifications: TbBell,
  Logout: TbLogout,
  Menu: TbMenu2,
  Close: TbX,
  Plus: TbPlus,
  Calendar: TbCalendar,
  Location: TbMapPin,
  User: TbUser,
  Search: TbSearch,
  Filter: TbFilter,
  Download: TbDownload,
  View: TbEye,
  Edit: TbEdit,
  Delete: TbTrash,
  Check: TbCheck,
  Alert: TbAlertTriangle,
  Upload: TbUpload,
  Camera: TbCamera,
};
